[package]
name = "rustc-bug"
version = "0.1.0"
authors = ["Emilio Cobos Álvarez <emilio@crisal.io>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cssparser = "0.27"
